Repository naengmyeon-pong/ft_transcendence, pull requests merged in 2023-08, with the labels that each got.

#50 Fix/전적 엔티티 변경#47
  backend/src/game/game.service.ts
  backend/src/record/record.controller.ts
  backend/src/record/record.entity.ts
  backend/src/record/record.repository.ts
  backend/src/record/record.service.ts
  backend/src/user/user.entitiy.ts
  backend/test_query.sql
Labels: enhancement

#51 Feat/2fa 회원가입 및 로그인 기능 구현#46
  backend/src/main.ts
  backend/src/two-factor-auth/dto/two-factor-auth-code.dto.ts
  backend/src/two-factor-auth/two-factor-auth.controller.ts
  backend/src/two-factor-auth/two-factor-auth.service.ts
  backend/src/user/dto/user.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
  backend/tsconfig.json
  backend/tsconfig.paths.json
  client/src/pages/user/2fa/index.tsx
  client/src/pages/user/login/index.tsx
  client/src/pages/user/signup/index.tsx
Labels: enhancement

#54 docs: 전적 파트 swagger 작성
  backend/src/record/record.controller.ts
Labels: documentation

#56 docs: 2FA 파트 swagger 명세 작성
  backend/src/two-factor-auth/dto/two-factor-auth-code.dto.ts
  backend/src/two-factor-auth/two-factor-auth.controller.ts
Labels: documentation

#59 fix: record에 user를 join하는 과정에서 암호가 포함되는 문제 해결
  backend/src/record/record.repository.ts
Labels: bug

#61 Feat 전적 페이지 생성/#52
  backend/src/record/dto/simple-record.dto.ts
  backend/src/record/record.controller.ts
  backend/src/record/record.repository.ts
  backend/src/record/record.service.ts
  client/package-lock.json
  client/package.json
  client/src/components/RecordItem.tsx
  client/src/pages/_app.tsx
  client/src/pages/user/record/index.tsx
  types/index.ts
  types/record/index.ts
  types/record/recent-record.interface.ts
Labels: enhancement

#62 Featchat swagger 작성 및 transaction 적용고려
  backend/src/chat/chat.controller.ts
  backend/src/chat/chat.service.ts
Labels: enhancement

#65 ✨ feat: 2fa 로그인 시 비밀번호 제거
  client/src/pages/user/login/index.tsx
Labels: enhancement

#71 Merge branch #49
  backend/insert_temp_data.sql
  backend/src/app.module.ts
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/dto/room.dto.ts
  backend/src/events/events.gateway.ts
  backend/src/game/game.gateway.ts
  backend/src/signup/signup.service.ts
  backend/src/user/user.controller.ts
  frontend/src/components/Block/index.tsx
  frontend/src/components/Chat/ListPage/CreateRoomForm.tsx
  frontend/src/components/Chat/ListPage/ShowRoomList.tsx
  frontend/src/components/Chat/ListPage/index.tsx
  frontend/src/components/Chat/RoomPage/ChatBox.tsx
  frontend/src/components/Chat/RoomPage/UserList.tsx
  frontend/src/components/Chat/RoomPage/UserNode.tsx
  frontend/src/components/Chat/RoomPage/index.tsx
  frontend/src/components/Chat/RoomPage/modal/ChatInvite.tsx
  frontend/src/components/Chat/RoomPage/modal/ModalPrint.tsx
  frontend/src/components/Chat/RoomPage/modal/MuteModal.tsx
  frontend/src/components/Chat/RoomPage/modal/ServiceModal.tsx
  frontend/src/components/Chat/RoomPage/service/Admin.ts
  frontend/src/components/Chat/RoomPage/service/Ban.ts
  frontend/src/components/Chat/RoomPage/service/Block.ts
  frontend/src/components/Chat/RoomPage/service/Kick.ts
  frontend/src/components/Chat/RoomPage/service/Mute.ts
  frontend/src/components/GlobalModal/index.tsx
  frontend/src/components/MainLayout/Context.tsx
  frontend/src/components/MainLayout/CustomAppBar.tsx
  frontend/src/components/MainLayout/SideBar/BlockUserList.tsx
  frontend/src/components/MainLayout/SideBar/ConnectUserList.tsx
  frontend/src/components/MainLayout/SideBar/DM.tsx
  frontend/src/components/MainLayout/SideBar/FriendList.tsx
  frontend/src/components/MainLayout/SideBar/Profile.tsx
  frontend/src/components/MainLayout/SideBar/index.tsx
  frontend/src/components/UserProfileModal/DMButton.tsx
  frontend/src/components/UserProfileModal/Test.tsx
  frontend/src/components/UserProfileModal/index.tsx
  frontend/src/components/layout/MainLayout.tsx
  frontend/src/components/styled/modalStyle.ts
  frontend/src/constants/sidebar.ts
  frontend/src/hooks/useGlobalModal.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/main/chat/index.tsx
  frontend/src/states/dmUser.ts
  frontend/src/states/globalModal.ts
  frontend/src/states/userContext.ts
  frontend/src/types/GlobalModal.ts
  frontend/src/types/UserContext.ts
Labels: enhancement

#73 Feat/게임 일대일 매칭 구현#70
  frontend/src/components/Block/index.tsx
  frontend/src/components/Chat/ListPage/CreateRoomForm.tsx
  frontend/src/components/Chat/ListPage/ShowRoomList.tsx
  frontend/src/components/Chat/RoomPage/ChatBox.tsx
  frontend/src/components/Chat/RoomPage/UserList.tsx
  frontend/src/components/Chat/RoomPage/UserNode.tsx
  frontend/src/components/Chat/RoomPage/index.tsx
  frontend/src/components/Chat/RoomPage/modal/ChatInvite.tsx
  frontend/src/components/UserProfileModal/DMButton.tsx
  frontend/src/components/layout/MainLayout/Context.tsx
  frontend/src/components/layout/MainLayout/CustomAppBar.tsx
  frontend/src/components/layout/MainLayout/SideBar/BlockUserList.tsx
  frontend/src/components/layout/MainLayout/SideBar/ConnectUserList.tsx
  frontend/src/components/layout/MainLayout/SideBar/DM.tsx
  frontend/src/components/layout/MainLayout/SideBar/FriendList.tsx
  frontend/src/components/layout/MainLayout/SideBar/Profile.tsx
  frontend/src/components/layout/MainLayout/SideBar/index.tsx
  frontend/src/components/layout/MainLayout/index.tsx
  frontend/src/pages/main/game/index.tsx
Labels: enhancement

#75 Feat/백엔드 소켓 통합#74
  backend/insert_temp_data.sql
  backend/src/app.module.ts
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.module.ts
  backend/src/chat/chat.service.ts
  backend/src/game/game.gateway.ts
  backend/src/game/game.module.ts
  backend/src/global-variable/global.block.ts
  backend/src/global-variable/global.socket.ts
  backend/src/signup/signup.module.ts
  backend/src/two-factor-auth/two-factor-auth.module.ts
  backend/src/user/user.gateway.ts
  backend/src/user/user.module.ts
  backend/src/utils/jwt-custom.module.ts
  backend/src/utils/multer.config.ts
  backend/src/utils/typeorm.config.ts
  frontend/src/components/Record/SimpleRecord.tsx
  frontend/src/components/UserProfileModal/Game.tsx
  frontend/src/components/UserProfileModal/index.tsx
  frontend/src/components/layout/MainLayout/index.tsx
  frontend/src/pages/main/game/index.tsx
  frontend/src/states/inviteGame.ts
  frontend/src/states/userContext.ts
  types/game/index.ts
  types/game/invite-game-info.interface.ts
Labels: bug, enhancement

#78 Feat/전적 페이지 구현#70
  backend/src/game/game.gateway.ts
  backend/src/record/dto/record-summary.dto.ts
  backend/src/record/record.controller.ts
  backend/src/record/record.module.ts
  backend/src/record/record.repository.ts
  backend/src/record/record.service.ts
  frontend/src/components/Record/DetailRecord.tsx
  frontend/src/components/Record/RecordSummary.tsx
  frontend/src/components/Record/RecordTable.tsx
  frontend/src/components/Record/TabPanel.tsx
  frontend/src/components/Record/TablePaginationActions.tsx
  frontend/src/components/UserProfileModal/index.tsx
  frontend/src/components/layout/MainLayout/index.tsx
  frontend/src/components/styled/modalStyle.ts
  frontend/src/pages/user/record/index.tsx
Labels: enhancement

#84 Feat/로그인 회원가입 예외처리 추가#83
  backend/src/game/game.gateway.ts
  backend/src/game/game.service.ts
  backend/src/user/dto/user.dto.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/apiManager.ts
  frontend/src/api/auth.ts
  frontend/src/components/hoc/withAuth.tsx
  frontend/src/components/layout/MainLayout/AppBar/index.tsx
  frontend/src/pages/user/2fa/index.tsx
  frontend/src/pages/user/auth/index.tsx
  frontend/src/pages/user/login/index.tsx
  frontend/src/pages/user/record/index.tsx
  frontend/src/pages/user/signup/index.tsx
  frontend/src/utils/token.ts
Labels: enhancement

#87 Feat/전적 cascade 설정#86
  backend/src/game/game.service.ts
  backend/src/record/record.entity.ts
  frontend/src/components/layout/MainLayout/AppBar/index.tsx
Labels: enhancement

#88 Feat/비밀번호 초기화 페이지 기능 구현#85
  backend/src/signup/signup.controller.ts
  backend/src/signup/signup.service.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
  frontend/src/components/layout/MainLayout/AppBar/index.tsx
  frontend/src/pages/user/auth/index.tsx
  frontend/src/pages/user/login/index.tsx
  frontend/src/pages/user/reset-password/index.tsx
  frontend/src/pages/user/setting/index.tsx
  frontend/src/states/passwordReset.ts
Labels: enhancement

#89 Feat/친구목록 온라인표시 77
  backend/src/app.module.ts
  backend/src/chat/chat.controller.ts
  backend/src/chat/chat.entity.ts
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.module.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/dto/partial-room.dto.ts
  backend/src/dm/dm.controller.ts
  backend/src/dm/dm.gateway.ts
  backend/src/dm/dm.module.ts
  backend/src/dm/dm.service.ts
  backend/src/friend/friend.controller.ts
  backend/src/friend/friend.gateway.ts
  backend/src/friend/friend.module.ts
  backend/src/friend/friend.service.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.gateway.ts
  frontend/src/components/layout/MainLayout/SideBar/DM.tsx
  frontend/src/components/layout/MainLayout/index.tsx
Labels: enhancement

#92 Feat/마이페이지 기능 구현#90
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
  frontend/src/components/layout/MainLayout/AppBar/index.tsx
  frontend/src/components/layout/MainLayout/SideBar/Profile.tsx
  frontend/src/components/layout/MainLayout/index.tsx
  frontend/src/components/signup/ImageUpload.tsx
  frontend/src/hooks/useProfileImage.ts
  frontend/src/pages/user/setting/index.tsx
  frontend/src/states/profileImage.ts
  frontend/src/types/ProfileImage.ts
Labels: enhancement

#95 🐛 fix: 프로필 조회 대상의 아이디로 API 요청하도록 수정
  frontend/src/components/Record/RecordSummary.tsx
  frontend/src/components/Record/RecordTable.tsx
  frontend/src/components/UserProfileModal/index.tsx
Labels: bug

#97 Feat/게임 초대 기능#79
  backend/src/game/game.gateway.ts
  backend/src/game/game.service.ts
  backend/src/game/types/game-user.interface.ts
  backend/src/game/types/type-mode.enum.ts
  backend/src/record/record.service.ts
  backend/src/user/user.gateway.ts
  frontend/src/components/Chat/RoomPage/UserNode.tsx
  frontend/src/components/UserProfileModal/Game.tsx
  frontend/src/components/UserProfileModal/index.tsx
  frontend/src/components/game/InviteGame.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/AlarmProps.ts
  frontend/src/components/layout/MainLayout/AppBar/Alarm/Chat/index.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/Game/Action.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/Game/Title.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/Game/index.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/GameAlarm.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/index.tsx
  frontend/src/components/layout/MainLayout/SideBar/FriendList.tsx
  types/game/invite-game-info.interface.ts
Labels: bug, enhancement

#99 Fix/게임 초대 머지 충돌#98
  backend/src/game/game.gateway.ts
  frontend/src/components/layout/MainLayout/AppBar/index.tsx
Labels: bug

#102 Feat/url 접근 시 유저 정보 확인 추가#96
  backend/src/signup/signup.controller.ts
  frontend/src/api/auth.ts
  frontend/src/components/Record/RecordSummary.tsx
  frontend/src/components/hoc/withAuth.tsx
  frontend/src/components/layout/MainLayout/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/user/2fa/index.tsx
  frontend/src/pages/user/reset-password/index.tsx
  frontend/src/pages/user/setting/index.tsx
  frontend/src/pages/user/signup/index.tsx
Labels: enhancement

#105 Fix/게임 참여 시 유저 정보를 찾아오지 못하는 문제 수정#103
  backend/src/game/game.gateway.ts
Labels: bug

#107 Fix/전적 파트 미사용 파일 삭제#106
  backend/src/record/mode/mode.controller.ts
  backend/src/record/mode/mode.module.ts
  backend/src/record/mode/mode.service.ts
  backend/src/record/type/type.controller.ts
  backend/src/record/type/type.module.ts
  backend/src/record/type/type.service.ts
Labels: enhancement

#109 fix: 토큰 만료시 예외처리
  frontend/src/components/Chat/ListPage/CreateRoomForm.tsx
  frontend/src/components/Chat/ListPage/ShowRoomList.tsx
  frontend/src/components/Chat/ListPage/index.tsx
  frontend/src/components/Chat/RoomPage/UserList.tsx
  frontend/src/components/Chat/RoomPage/index.tsx
  frontend/src/components/Chat/RoomPage/modal/ChatInvite.tsx
  frontend/src/components/layout/MainLayout/AppBar/index.tsx
  frontend/src/components/layout/MainLayout/Context.tsx
  frontend/src/components/layout/MainLayout/SideBar/DM.tsx
  frontend/src/components/layout/MainLayout/SideBar/index.tsx
  frontend/src/components/layout/MainLayout/index.tsx
  frontend/src/states/tokenExpired.ts
Labels: enhancement

#110 Fix/게임 몰수패 처리#108
  backend/src/game/game.gateway.ts
  backend/src/game/game.service.ts
  backend/src/user/user.gateway.ts
  frontend/src/components/layout/MainLayout/index.tsx
  frontend/src/pages/main/game/index.tsx
  frontend/src/pages/user/login/index.tsx
Labels: bug, enhancement

#114 feat: friend 전역클래스 추가
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.service.ts
  backend/src/friend/friend.gateway.ts
  backend/src/friend/friend.service.ts
  backend/src/game/game.gateway.ts
  backend/src/global-variable/global-variable.module.ts
  backend/src/global-variable/global.block.ts
  backend/src/global-variable/global.friend.ts
  backend/src/user/user.gateway.ts
Labels: enhancement

#115 Feat/oauth 로그인 기능 추가#112
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  frontend/src/components/layout/MainLayout/AppBar/LogOut.tsx
  frontend/src/pages/main/game/index.tsx
  frontend/src/pages/user/auth/index.tsx
  frontend/src/pages/user/login/index.tsx
  frontend/src/states/loginState.ts
  frontend/src/types/LoginState.ts
  types/user/oauth.ts
Labels: enhancement

#117 Feat/게임 뒤로가기 처리#116
  backend/src/game/game.gateway.ts
  backend/src/user/user.service.ts
  frontend/src/components/Chat/RoomPage/modal/ChatInvite.tsx
  frontend/src/components/Chat/RoomPage/service/Kick.ts
  frontend/src/components/RecordItem.tsx
  frontend/src/components/UserProfileModal/DMButton.tsx
  frontend/src/components/UserProfileModal/Game.tsx
  frontend/src/components/game/Choice/GameAction.tsx
  frontend/src/components/game/Choice/GameMode.tsx
  frontend/src/components/game/Choice/GameType.tsx
  frontend/src/components/game/Game.tsx
  frontend/src/components/game/InviteGame.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/Game/Action.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/Game/Title.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/index.tsx
  frontend/src/components/layout/MainLayout/SideBar/DM.tsx
  frontend/src/components/layout/MainLayout/SideBar/FriendList.tsx
  frontend/src/components/layout/MainLayout/SideBar/index.tsx
  frontend/src/components/layout/MainLayout/index.tsx
  frontend/src/pages/main/chat/index.tsx
  frontend/src/pages/user/2fa/index.tsx
  frontend/src/pages/user/setting/index.tsx
  frontend/src/pages/user/signup/index.tsx
Labels: bug, enhancement

#121 refector: SideBar 친구목록, DM, 차단목록 각각 폴더추가 및 컴포넌트 나눔
  frontend/src/components/UserProfileModal/DMButton.tsx
  frontend/src/components/layout/MainLayout/SideBar/BlockList/index.tsx
  frontend/src/components/layout/MainLayout/SideBar/ConnectUserList.tsx
  frontend/src/components/layout/MainLayout/SideBar/DM.tsx
  frontend/src/components/layout/MainLayout/SideBar/DMList/DMList.tsx
  frontend/src/components/layout/MainLayout/SideBar/DMList/DMPrint.tsx
  frontend/src/components/layout/MainLayout/SideBar/DMList/DMUser.tsx
  frontend/src/components/layout/MainLayout/SideBar/DMList/Message.tsx
  frontend/src/components/layout/MainLayout/SideBar/DMList/index.tsx
  frontend/src/components/layout/MainLayout/SideBar/DisplayButtonGroup/index.tsx
  frontend/src/components/layout/MainLayout/SideBar/DisplayList.tsx
  frontend/src/components/layout/MainLayout/SideBar/FriendList/FindUser.tsx
  frontend/src/components/layout/MainLayout/SideBar/FriendList/Friend.tsx
  frontend/src/components/layout/MainLayout/SideBar/Profile/index.tsx
  frontend/src/components/layout/MainLayout/SideBar/index.tsx
  frontend/src/states/dmUser.ts
  frontend/src/states/userContext.ts
Labels: enhancement

#125 Fix/게임 초대 예외 처리#118
  backend/src/game/game.gateway.ts
  backend/src/game/game.service.ts
  frontend/src/components/game/Choice/GameAction.tsx
  frontend/src/components/game/Game.tsx
  frontend/src/components/game/InviteGame.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/Game/Action.tsx
  frontend/src/components/layout/MainLayout/AppBar/Alarm/index.tsx
  frontend/src/pages/main/game/index.tsx
Labels: bug, enhancement
